services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ares
      POSTGRES_PASSWORD: Hl5r6VTW
      POSTGRES_DB: bemestar
    ports:
      - "54321:54321"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: