version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: brigia-backend
    command: >
      sh -c "
        if [ \"$ENV\" = 'prod' ]; then
          uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT};
        else
          uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload;
        fi
      "
    environment:
      - ENV=${ENV}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
    container_name: brigia-frontend
    command: >
      sh -c "
        if [ \"$ENV\" = 'prod' ]; then
          npm run build && npx serve -s dist -l ${FRONTEND_PORT};
        else
          npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT};
        fi
      "
    environment:
      - ENV=${ENV}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"