services:
  backend:
    build:
      context: ./backend
      args:
        ENV: ${ENV}
    container_name: brigia-backend
    command: >
      sh -c "
        if [ \"$ENV\" = 'prod' ]; then
          uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT};
        else
          uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload;
        fi
      "
    environment:
      - ENV=${ENV}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - SUPABASE_PROJECT_ID=${SUPABASE_PROJECT_ID}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${BACKEND_URL}
    container_name: brigia-frontend
    command: >
      sh -c "
        if [ \"$ENV\" = 'prod' ]; then
          npm run build && npx serve -s dist -l ${FRONTEND_PORT};
        else
          npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT};
        fi
      "
    environment:
      - ENV=${ENV}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"