version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8008:8008"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: frontend-app
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
