services:

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brigia-bemestar
    healthcheck:
      # MUITO IMPORTANTE: Garanta que o nome do banco de dados aqui é 'brigia-bemestar'
      # e que o usuário é 'postgres' (ou o usuário que você está usando)
      test: ["CMD-SHELL", "pg_isready -U postgres -d brigia-bemestar"]
      interval: 5s       # Verifica a cada 5 segundos
      timeout: 5s        # Tempo limite para o teste
      retries: 10        # Tenta 10 vezes antes de considerar unhealthy
      start_period: 30s  # Dá 30 segundos para o DB iniciar antes de começar os testes

  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
