// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcxglvtwghoinbhklvxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjeGdsdnR3Z2hvaW5iaGtsdnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNzI1ODUsImV4cCI6MjA1NTg0ODU4NX0.1zN0N2cOPyrJhjfXAaIwa0a_7WptbpZeN5bCymKqJxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);