--MEDICOS
insert into procedimento (nome, especialidade_id) SELECT 'ECG + CONSULTA', id from especialidade where nome like 'CARDIO + ECG';
insert into procedimento (nome, especialidade_id) SELECT 'EXAME ECOCARDIOGRAMA', id from especialidade where nome like 'CARDIO ECOCARDIOGRAMA';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA CARDIOLOGISTA', id from especialidade where nome like 'CARDIOLOGISTA';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA CLINICO GERAL', id from especialidade where nome like 'CLINICO GERAL';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA DERMATOLOGISTA', id from especialidade where nome like 'DERMATOLOGISTA';
insert into procedimento (nome, especialidade_id) SELECT 'CURETAGEM 1 LESÃO GRANDE OU 05 LESÕES PEQUENAS', id from especialidade where nome like 'DERMATOLOGISTA  - CURETAGEM ROSTO';
insert into procedimento (nome, especialidade_id) SELECT 'VALOR A CADA 05 LESÕES SE TIVER + VER VALOR C/DR', id from especialidade where nome like 'DERMATOLOGISTA  - CURETAGEM CORPO';
insert into procedimento (nome, especialidade_id) SELECT 'ATÉ 05', id from especialidade where nome like 'DERMATOLOGISTA - CRIOTERAPIA ';
insert into procedimento (nome, especialidade_id) SELECT 'INCISÃO LESÃO - ROSTO', id from especialidade where nome like 'DERMATOLOGISTA - INCISÃO LESÃO - ROSTO';
insert into procedimento (nome, especialidade_id) SELECT 'INCISÃO LESÃO - CORPO', id from especialidade where nome like 'DERMATOLOGISTA - INCISÃO LESÃO - CORPO';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA GINECOLOGISTA', id from especialidade where nome like 'GINECOLOGISTA';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA PRE NATAL', id from especialidade where nome like 'GINECOLOGISTA - PRE NATAL';
insert into procedimento (nome, especialidade_id) SELECT 'PREV +CONSULTA ', id from especialidade where nome like 'GINECOLOGISTA + PREVENTIVO';
insert into procedimento (nome, especialidade_id) SELECT 'COLOCAÇÃO DIU (não incluso DIU)', id from especialidade where nome like 'GINECOLOGISTA COLOCAÇÃO DIU';
insert into procedimento (nome, especialidade_id) SELECT 'CONS + RET DO DIU', id from especialidade where nome like 'GINECOLOGISTA RETIRADA DIU';
insert into procedimento (nome, especialidade_id) SELECT 'COLOCAÇÃO IMPLANON (não incluso implanon)', id from especialidade where nome like 'GINECOLOGISTA IMPLANON';
insert into procedimento (nome, especialidade_id) SELECT 'CONS + RET DO IMPLANON', id from especialidade where nome like 'GINECOLOGISTA RETIRADA IMPLANON';
insert into procedimento (nome, especialidade_id) SELECT 'RETI DO DIU - PCTE DRA', id from especialidade where nome like 'GINECOLOGISTA RETIRADA DIU';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA NEUROLOGISTA', id from especialidade where nome like 'NEUROLOGISTA';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA NUTRICIONISTA', id from especialidade where nome like 'NUTRICIONISTA';
insert into procedimento (nome, especialidade_id) SELECT 'BIOPEDANCIA', id from especialidade where nome like 'NUTRICIONISTA';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA OFTALMOLOGISTA', id from especialidade where nome like 'OFTALMOLOGISTA';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA ORTOPEDISTA', id from especialidade where nome like 'ORTOPEDISTA';
insert into procedimento (nome, especialidade_id) SELECT 'INFILTRAÇAO', id from especialidade where nome like 'ORTOPEDISTA / INFILTRAÇAO';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA OTORRINO', id from especialidade where nome like 'OTORRINO';
insert into procedimento (nome, especialidade_id) SELECT 'CONSULTA VASCULAR', id from especialidade where nome like 'VASCULAR';
insert into procedimento (nome, especialidade_id) SELECT 'APLICAÇÃO DE VARICOSE', id from especialidade where nome like 'VASCULAR';
insert into procedimento (nome, especialidade_id) SELECT 'APLICAÇÃO DE ESPUMA', id from especialidade where nome like 'VASCULAR';