--ULTRASSOM
INSERT INTO especialidade (nome) VALUES ('ULTRASSOM');

insert into procedimento (codigo, nome, especialidade_id) SELECT '50000406', 'US MAP. ENDOMETRIOSE', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901475', 'ECODOPPLER ARTERIAL ( 1 PERNA )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000168', 'ECODOPPLER ARTERIAL ( 2 LADOS )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901483', 'ECODOPPLER VENOSO ( 1 PERNA )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000167', 'ECODOPPLER VENOSO ( 2 LADOS )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901181', 'US AB INF - FEM', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000135', 'US AB INF - FEM (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000134', 'US AB INF - MASC (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000133', 'US AB SUP (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000137', 'US AB TOTAL (APENDICITE)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901572', 'US AB TOTAL (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901173', 'US AB INF - MASC', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000139', 'US AP URINÁRIO - FEM (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000138', 'US AP URINÁRIO - MASC (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901130', 'US AB SUP', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000153', 'US BOLSA ESCROTAL (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901394', 'US DOOPLER AORTA/RENAIS', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901360', 'US DOOPLER CAROTIDAS/VERT', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000148', 'US GINECOL. TV ( C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000152', 'US MAMAS (FEM / MASC) ( COM DOOPLER )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901122', 'US AB TOTAL', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901262', 'US MORF. 1º TRIM ( 10 A 14 SEM)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000146', 'US MORF. 2º TRIM ( 20 A 24 SEM)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000157', 'US ANTEBRAÇO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901246', 'US OBST. ( C/ DOOPLER )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000212', 'US OBST. (C/ TN )-GEMELAR', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901254', 'US OBST. (C/ TRANSL. NUCAL )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000144', 'US OBST. 1º TRIM ( TV - C/ DOOPLER )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901289', 'US OBST. GEM(CADA FETO) C/DOOP', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000174', 'US REGIAO CERVICAL (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901505', 'US OBST. (PERFIL BIOF. FETAL)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000151', 'US TIREOIDE ( COM DOPPLER )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901157', 'US AP URINÁRIO - FEM', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901165', 'US AP URINÁRIO - MASC', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901220', 'US ARTICULAÇÃO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000165', 'US AXILA (CADA LADO)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901041', 'US TORAXICA EXTRA-CARDIACA', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000175', 'US BOLSA ESCROTAL', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000158', 'US COTOVELO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000160', 'US DEDO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000136', 'US FIGADO E VIAS BILIARES ', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000147', 'US GINECOL. PELVICA (ABD INF)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901408', 'US DOOPLER AORTA/ILIACAS', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901300', 'US GINECOL. TV', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000150', 'US GLANDULAS SALIVARES', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000161', 'US JOELHO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000149', 'US LOMBAR ( CADA LADO )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901114', 'US MAMAS (FEM / MASC)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901386', 'US DOOPLER ESTRUTURA ISOL', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000155', 'US MAO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901297', 'US OBST. 1º TRIM ( TV )', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000398', 'US OBST. 2º, 3º TRIM', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901270', 'US OBST. GEM(CADA FETO)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000156', 'US OMBRO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000164', 'US PE (FACES VOLAR E PLANTAR)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000141', 'US PAREDE ABDOM (HERNIAS)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000154', 'US PARTES MOLES (LESOES ESPECIFICAS)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000166', 'US PENIS', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000143', 'US PROST. ABDOM', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901335', 'US PROST. TRANSRETAL', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000159', 'US PUNHO ', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000163', 'US QUADRIL ADULTO (CADA LADO)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901211', 'US REGIAO CERVICAL', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000142', 'US REGIAO INGUINAL (HERNIA)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901203', 'US TIREOIDE', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000162', 'US TORNOZELO', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901165', 'US AP URINARIO - MASC', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000139', 'US AP URINARIO - FEM (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000138', 'US AP URINARIO - MASC (C/ DOOPLER)', id from especialidade where nome like 'ULTRASSOM';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40901408', 'US DOOPLER AORTA/ILÍACAS', id from especialidade where nome like 'ULTRASSOM';