--LAB
insert into procedimento (codigo, nome, especialidade_id) SELECT '40305783','17-HIDROXICORTICOSTEROIDES', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40311236','2,5 HEXANODIONA URINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313190','ABS. ATOMICA METAIS(ARSENICO)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313018','AC DELTA AMINOLEVULÍNICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000255','AC FORMICO URINARIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'ACIDO FOLICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301087','ACIDO FOLICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313042','ACIDO HIPURICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313050','ACIDO MANDELICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313069','ACIDO METILHIPURICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316793','ACIDO TRANS MUCONICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313280','ACIDO TRICLORACETICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301150','ACIDO URICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'ACTH - HORMONIO ADRENOCORTICOTROFICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301222','ALBUMINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301230','ALDOLASE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301257','ALFA 1- GLICOPROTEINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316068','ALFA-FETOPROTEINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301281','AMILASE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316076','ANDROSTENEDIONA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000250','ANTI CCP', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'ANTI DNA ATIVO 2 HELICE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'ANTI ENA RNP', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306259','ANTI ENDOMIZIO IGA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000269','ANTI ENDOMIZIO IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000270','ANTI ENDOMIZIO IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306950','ANTI HBC IgG (HEPATITE B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306968','ANTI HBC IgM (HEPATITE B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306976','ANTI HBE (HEPATITE B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306992','ANTI HBS (HEPATITE B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306933','ANTI HVA IgG (HEPATITE A)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306941','ANTI HVA IgM (HEPATITE A)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'ANTI SM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40308553','ANTI TRANSG TECIDUAL - IGA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306089','ANTI-LA / SSB', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306119','ANTI-RO / SSA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316157','ANTI-TPO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310418','ANTIBIOGRAMA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'ANTICOAGULANTE LUPICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306305','ANTIGLIADINA (GLÚTEN) - IgA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306313','ANTIGLIADINA (GLÚTEN) - IgG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306321','ANTIGLIADINA (GLÚTEN) - IgM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306348','ANTIMICROSSOMAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306445','ASO (ASLO - PESQ LATEX)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306461','AVIDEZ DE IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306470','B2 MICROBULINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000262','BACT + EPU', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310060','BACT SECREÇÃO VAGINAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'BACTERIOSCOPIA ( GRAM)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'BETA HCG MASCULINO - TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40305759','BETA HCG-QUALIT', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40305767','BETA HCG-QUANT', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'BILIRRUBINAS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301397','BILLIRRUBINAS DIR/IND/TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '30101077','BIÓPSIA - MATERIAL CLÍNICA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306500','BRUCELA - IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306518','BRUCELA - IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CA 15-3', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CA 19-9', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CA 72-4', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304795','CÉLULAS LE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CADIOLPINA IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CADIOLPINA IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CADMIO NA URINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301400','CALCIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301419','CALCIO IONICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000257','CALCIO SÉRICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40321363','CANABINOIDE - URINA (MACONHA)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313093','CARBOXIHEMOGLOBINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306593','CAXUMBA, IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306607','CAXUMBA, IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316122','CEA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307964','CHAGAS HEMOAGLUTINAÇÃO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306631','CHLAMYDIA - IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306640','CHLAMYDIA - IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313107','CHUMBO (URINA)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306658','CISTICERCOSE, AC', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306666','CITO IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306674','CITO IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CITOMEGALOVIRUS IgG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CK - MB', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301508','CLEARANCE DE CREATININA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CLEARENCE DE UREIA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40312046','CLORETOS - CL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CLORO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304922','COAGULOGRAMA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301567','COBRE-SANGUINIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301605','COLESTEROL TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000254','COLESTEROL TOTAL + FRAÇÕES', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302695','COLESTEROL VLDL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313115','COLINESTERASE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306704','COMPLEMENTO C3', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306712','COMPLEMENTO C4', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304108','COOMBS DIRETO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304884','COOMBS INDIRETO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40303039','COPROLOGICO FUNC', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000263','COPROPARASITOLÓGICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316190','CORTISOL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CREATINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301630','CREATININA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301664','CREATINO FOSFOQ - MB-ATIVID - CPK', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301656','CREATINO FOSFOQ - MB-MASSA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313310','CROMO URINARIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310078','CULT CHLAMYDIA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000240','CULT ORORFARINGE ANTIB', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000241','CULT SEC OROFARINGE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310221','CULT SEC VAGINAL (STREPTOCOCCUS B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310124','CULTURA BACTERIANA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CULTURA DE SECREÇÃO VAGINAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000453','CULTURA DE URINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310183','CULTURA FEZES (COPROCULTURA)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000243','CULTURA GONORREIA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000244','CULTURA P/ MUCOPLASMA 55', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CULTURA PARA ESTREPTOCOCOS AGALACTIE (VAGINAL)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CULTURA PARA ESTREPTOCOCOS AGALACTIE (PERINEAL)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310140','CULTURA PARA FUNGOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000245','CULTURA SS E. COLI', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000246','CULTURA UREAPLASMA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CULTURA URINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310205','CULTURA, MICOPLASMA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'CURVA GLICEMIA GESTANTE - JEJUM,60M,120M', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301680','CURVA GLICEMICA (4 DOSES)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000247','D DIMERO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'DENGUE IgG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'DENGUE Igm', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301729','DESIDROGENASE LACTICA - LDH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316211','DHEA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'DHT - DEHIDROTESTOOSTERONA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'DIMERO D', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301354','DOSAGEM APO A', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301761','ELETROFERESE DE PROTEINAS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304353','ELETROFORESE DE HEMOGLOBINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40311210','EPU (PARCIAL DE URINA)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40309312','ESPERMOGRAMA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316246','ESTRADIOL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316254','ESTRIOL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316262','ESTRONA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313140','ETANOL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'EXAME A FRESCO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306852','FAN', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40308030','FATOR REUMATOIDE (LÁTEX)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306860','FATOR REUMATOIDE QUANTITATIVO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40403173','FATOR RH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313158','FENOL (PARA BENZENO, FENOL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316270','FERRITINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301842','FERRO SÉRICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'FIBRINOGENIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313166','FLUOR (PARA FLUORETOS)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301850','FORMALDEIDO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301885','FOSFATSE ALCALINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301923','FOSFOLIPIDIOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301931','FOSOFORO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301958','FRUTOSAMINAS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316289','FSH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307735','FTA-ABS IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307743','FTA-ABS IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301990','GAMA GT', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302032','GLIC APOS CARGA COM GLICOSE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302040','GLICOSE (GLICEMIA DE JEJUM)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40303055','GORDURA FECAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304280','GRUPO ABO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40306984','HBeAg (HEPATITE B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316114','HBSAG - ANTIGENO AUSTRALIA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307018','HBSAG (HEPATITE B)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301583','HDL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310248','HEMOCULTURA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302733','HEMOGLOBINA GLICADA (FRAÇ A1C)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304361','HEMOGRAMA COMPLETO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307026','HEPATITE C - ANTI-HCV', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307085','HERPES SIMPLES - IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307093','HERPES SIMPLES - IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000248','HGT-DIABETE NO DEDO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307174','HIV I, HIV II', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302113','HOMOCISTEINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307263','IGE ALERGENO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307255','IGE ESPECIFICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307271','IGE TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307972','IMUNOF - MACHADO GUERREIRO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40321231','INDICE DE SATURAÇÃO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316360','INSULINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'INSULINA BASAL / JEJUM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'INSULINA LIVRE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304639','KTTP - TEMPO TROMBOPLAST', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302164','LACTOSE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'LACTOSE 15 MINUTOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'LACTOSE 30 MINUTOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'LACTOSE 45 MINUTOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'LACTOSE 60 MINUTOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'LACTOSE BASAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304116','LDH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40301591','LDL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'LEPTINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40303098','LEUCOCITOS E HEMACIAS(FEZES)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316335','LH ( HORMONIO LUTEINIZANTE)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302199','LIPASE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302210','LIPOPROTEINA A', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302229','LITIO (LITEMIA)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40305775','MACROPROLACTINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302237','MAGNESIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '28150279','MANGANES', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000264','MARCAD. TUMORAIS (CA 125)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000265','MARCAD. TUMORAIS (CA 15-3)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316378','MARCAD. TUMORAIS (CA 19.9)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000266','MARCAD. TUMORAIS (CA 72-4)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '28150163','MERCURIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313204','METANOL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313344','METIL ETIL ACETONA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '41301226','MIC UNHAS (DIRETO - LOCAL)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40311171','MICROALBUMINURIAM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40308340','MONONUCLEOSE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307565','MONONUCLEOSE-EPSTEIN BARR-IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307573','MONONUCLEOSE,ANTI-VCA(EBV)IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307581','MONONUCLEOSE,ANTI-VCA(EBV)IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302660','MUCOPROTEÍNAS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '28150198','NIQUEL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'OXIRUS, PESQUISA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'PAINEL DST - PCR', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40303110','PARASITOLOGICO (EPF)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40305465','PARATORMONIO - PTH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302750','PERFIL LIPÍDICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40312127','PERFIL REUMATOLOGICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000251','PESQ CHLAMYDIA A FRESCO + BAC', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310221','PESQ DE STREPTOCOCOS B', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000252','PESQ. CHLAMYDIA EM C. CERVICAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000261','PESQUISA PARA BK', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000260','PH FEZES', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304450','PLAQUETAS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304477','PLASMODIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302318','POTASSIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307123','PPD', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '41301099','PREVENTIVO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316408','PROGESTERONA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316416','PROLACTINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302385','PROT TOTAIS ALB/GLOB', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000253','PROT TOTAL + FRAÇ', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40308391','PROTEINA C REATIVA - ( QUANT )', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'PROTEINA TOTAIS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'PROTEINAS TOTAIS E FRAÇÕES', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'PROTEINURIA 24 HORAS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316130','PSA LIVRE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316149','PSA TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304558','RETICULOCITOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40310337','ROTAVIRUS, PESQUISA, ELISA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307697','RUBEOLA - IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307700','RUBEOLA - IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316459','S-DHEA (SULFATO)', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40303136','SANGUE OCULTO NAS FEZES', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'SELENIO SERICO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'SEROTONINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'SEXAGEM FETAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316300','SHBG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302423','SODIO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316440','SOMATOMEDINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302431','SUCCINIL ACETONA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40303020','SWAB ANAL ( OXIÚRIOS )', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40312380','SWAB FARINGEO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'T3 - REVERSO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316556','T3 - TRIIODOTIRONINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316467','T3 LIVRE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316483','T3 REVERSO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'T3 TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316491','T4 LIVRE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316548','T4 TOTAL - TIROXINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304590','TAP - TEMPO DE PROTROMBINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000259','TESTE DE GLÚTEM IGA E IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'TESTE DE TOLERANCIA A LACTOSE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000249','TESTE GEN INTOLERANCIA LACTOSE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'TESTOSTERONA BIOD.', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316505','TESTOSTERONA LIVRE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316513','TESTOSTERONA TOTAL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302504','TGO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302512','TGP', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316530','TIREOGLOBULINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000172','TOXICOLÃ“GICO - CABELO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000267','TOXICOLÃ“GICO - URINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307794','TOXOCARA CANNIS - IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307808','TOXOCARA CANNIS - IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307824','TOXOPLASMOSE IGG', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307832','TOXOPLASMOSE IGM', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302520','TRANSFERRINA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '50000268','TRANSGLUTAMINASE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302547','TRIGLICERIDEOS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316521','TSH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'TTPA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302580','UREIA', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307760','VDRL', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304370','VHS', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302601','VITAMINA A', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40316572','VITAMINA B12', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'VITAMINA C', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40302830','VITAMINA D', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'VITAMINA D 25 DIHIDROXI', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'VITAMINA D 25 OH', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT null,'VITAMINA E', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40307867','WAALER-ROSE', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40313328','ZINCO', id from especialidade where nome like 'LAB.';
insert into procedimento (codigo, nome, especialidade_id) SELECT '40304523','ZINCO PROTOPORFIRINA', id from especialidade where nome like 'LAB.';