services:
  postgres:
    image: postgres:15
    container_name: pg-local
    ports:
      - "6543:6543"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: